version: "3.7"

networks:
  laravel:
  app-shared:
    driver: bridge

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx_${APP_NAME}
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
      - app-shared

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_${APP_NAME}
    restart: unless-stopped
    ports:
      - '3001:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./php/composer/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel

  mysql:
    image: library/mysql:8
    container_name: mysql_${APP_NAME}
    restart: unless-stopped
    tty: true
    command: --innodb_use_native_aio=0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - laravel

  mysql_test:
    image: library/mysql:8
    container_name: mysql_test_${APP_NAME}
    restart: unless-stopped
    tty: true
    command: --innodb_use_native_aio=0
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_test:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - laravel

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_${APP_NAME}
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
      - app-shared

  composer:
    build:
      context: ./php/composer
      dockerfile: Dockerfile
    container_name: composer_${APP_NAME}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer']
    networks:
      - laravel

  artisan:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: artisan_${APP_NAME}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      - laravel

  npm:
    image: library/node
    container_name: npm${APP_NAME}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel


